# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'TestingFramework', :path => "../TestingFramework/"
pod 'TestingFramework', :git => 'https://github.com/anoopkr207/TestingFramework.git', :branch => 'main'
  # Pods for ExampleDemo

  target 'ExampleDemoTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'ExampleDemoUITests' do
    # Pods for testing
  end

end
