# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TestingFramework', :path => "../TestingFramework/"

  # Pods for ExampleDemo

  target 'ExampleDemoTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'ExampleDemoUITests' do
    # Pods for testing
  end

end
